# Generated by Django 5.1.1 on 2025-01-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
