# Generated by Django 5.1.1 on 2025-01-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0002_manufacturer_colour_manufacturer_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image1',
            field=models.ImageField(null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
