# Generated by Django 5.1.1 on 2025-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0003_manufacturer_image1_manufacturer_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='villa'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
